DROP TABLE SALGRADE;

CREATE TABLE SALGRADE 
( 
  GRADE number(5) NOT NULL,
  LSAL number(8),
  HSAL number(8),
    CONSTRAINT SALGRADE_GRADE_PK PRIMARY KEY (GRADE)
);            --테이블명_컬럼명_제약조건종류 

INSERT INTO SALGRADE(GRADE, LSAL, HSAL) VALUES (1, 500, 2999);
INSERT INTO SALGRADE(GRADE, LSAL, HSAL) VALUES (2, 3000, 3799);
INSERT INTO SALGRADE(GRADE, LSAL, HSAL) VALUES (3, 3800, 5199);
INSERT INTO SALGRADE(GRADE, LSAL, HSAL) VALUES (4, 5200, 9999);
INSERT INTO SALGRADE(GRADE, LSAL, HSAL) VALUES (5, 10000, 50000);
 
commit; 

SELECT * FROM SALGRADE; 

